project_name: wiretrustee
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
nfpms:
  - maintainer: Wiretrustee <wiretrustee@wiretrustee.com>
    description: Wiretrustee project.
    homepage: https://wiretrustee.com/
    formats:
      - deb
      - rpm
    contents:
      - src: release_files/wiretrustee.service
        dst: /lib/systemd/system/wiretrustee.service

      - src: release_files/wiretrustee.json
        dst: /etc/wiretrustee/wiretrustee.json
        type: "config|noreplace"

    scripts:
      postinstall: "release_files/post_install.sh"
