project_name: wiretrustee-ui
builds:
  - id: wiretrustee-ui-darwin
    dir: client/ui
    binary: wiretrustee-ui
    env: [CGO_ENABLED=1]

    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w -X github.com/wiretrustee/wiretrustee/client/ui/system.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - load_wgnt_from_rsrc

archives:
  - builds:
      - wiretrustee-ui-darwin

brews:
  -
    tap:
      owner: wiretrustee
      name: homebrew-client
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Wiretrustee
      email: wiretrustee@wiretrustee.com
    description: Wiretrustee project.
    download_strategy: CurlDownloadStrategy
    homepage: https://wiretrustee.com/
    license: "BSD3"
