version: "3"
services:
  #UI dashboard
  dashboard:
    image: wiretrustee/dashboard:main
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - AUTH0_DOMAIN: <YOUR AUTH0 DOMAIN>
      - AUTH0_CLIENT_ID: <YOUR AUTH0 CLIENT ID>
      - AUTH0_AUDIENCE: <YOUR AUTH0 AUDIENCE>
      - WIRETRUSTEE_MGMT_API_ENDPOINT: <YOUR WIRETRUSTEE MANAGEMENT API ENDPOINT>
#      - NGINX_SSL_PORT: 443
#      - LETSENCRYPT_DOMAIN: <YOUR DOMAIN>
#      - LETSENCRYPT_EMAIL: <YOUR EMAIL>
  # Signal
  signal:
    image: wiretrustee/signal:latest
    restart: unless-stopped
    volumes:
      - wiretrustee-mgmt:/var/lib/wiretrustee
    ports:
      - 10000:10000
#     # port and command for Let's Encrypt validation
#      - 443:443
#    command: ["--letsencrypt-domain", "<YOUR-DOMAIN>"]
  # Management
  management:
    image: wiretrustee/management:latest
    restart: unless-stopped
    volumes:
      - wiretrustee-mgmt:/var/lib/wiretrustee
      - ./config.json:/etc/wiretrustee/management.json
    ports:
      - 33073:33073
#     # port and command for Let's Encrypt validation
#      - 443:443
#    command: ["--letsencrypt-domain", "<YOUR-DOMAIN>"]
  # Coturn
  coturn:
    image: coturn/coturn
    restart: unless-stopped
    domainname: stun.wiretrustee.com
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
#      - ./privkey.pem:/etc/coturn/private/privkey.pem:ro
#      - ./cert.pem:/etc/coturn/certs/cert.pem:ro
    network_mode: host
volumes:
  wiretrustee-mgmt:
  wiretrustee-signal:
