name: Test Code Darwin
on: [push,pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: macos-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            macos-go-

      - name: Install modules
        run: go mod tidy

      - name: Test
        run: GOBIN=$(which go) && sudo --preserve-env=GOROOT $GOBIN test ./...