name: Test Code Darwin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: macos-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            macos-go-

      - name: Install modules
        run: go mod tidy

      - name: Test
        run: go test -exec 'sudo --preserve-env=CI' -timeout 5m -p 1 ./...
